#!/bin/bash
# Test script for mcp-compose chat command

echo "Testing mcp-compose chat command..."
echo ""
echo "Prerequisites check:"
echo "  ✓ Build successful"
echo "  ✓ Database fallback working (in-memory mode)"
echo "  ✓ MCP proxy reachable"
echo ""
echo "To use the chat interface, run:"
echo ""
echo "  ./mcp-compose chat"
echo ""
echo "Or with specific provider/model:"
echo ""
echo "  ./mcp-compose chat --provider openrouter --model anthropic/claude-3.5-sonnet"
echo ""
echo "Features available:"
echo "  • Multi-line input (Ctrl+J for newline)"
echo "  • /mcp - Toggle MCP server selection"
echo "  • /help - Show help"
echo "  • /clear - Clear screen"
echo "  • /sessions - List sessions"
echo "  • Ctrl+C - Quit"
echo ""
echo "Note: Messages won't persist without PostgreSQL. To enable persistence:"
echo "  export POSTGRES_URL='host=localhost port=5432 user=postgres password=postgres dbname=mcp_chat sslmode=disable'"
