-- Migration: Seed marketplace data
-- Version: 002
-- Description: Populate marketplace with initial MCP servers

-- Ensure categories exist (ON CONFLICT to avoid duplicates)
INSERT INTO marketplace_categories (name, display_name, description, icon, sort_order) VALUES
    ('filesystem', 'File System', 'File and directory operations', 'folder', 1),
    ('database', 'Databases', 'Database connectivity and tools', 'database', 2),
    ('search', 'Search & Web', 'Web search and data fetching', 'search', 3),
    ('productivity', 'Productivity', 'Note-taking and task management', 'clipboard', 4),
    ('development', 'Development', 'Developer tools and utilities', 'code', 5),
    ('ai', 'AI & ML', 'AI and machine learning tools', 'brain', 6),
    ('communication', 'Communication', 'Messaging and collaboration', 'message-square', 7),
    ('storage', 'Storage & Memory', 'Persistent storage and memory', 'hard-drive', 8)
ON CONFLICT (name) DO NOTHING;

-- Insert initial MCP servers
INSERT INTO marketplace_servers (
    name, display_name, description, docker_image, npm_package, category,
    tags, protocol, capabilities, config_template, featured, downloads,
    rating, author, repository_url, documentation_url, version
) VALUES
    (
        'filesystem',
        'Filesystem',
        'Provides file system operations including read, write, and directory management. Essential for AI agents that need to interact with local files and directories.',
        NULL,
        '@modelcontextprotocol/server-filesystem',
        'filesystem',
        ARRAY['files', 'directories', 'read', 'write', 'essential'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem", "/allowed/path"]}',
        true,
        1250,
        4.8,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
        '0.4.0'
    ),
    (
        'memory',
        'Memory',
        'Persistent key-value storage with MCP integration. Allows AI agents to store and retrieve information across sessions.',
        NULL,
        '@modelcontextprotocol/server-memory',
        'storage',
        ARRAY['storage', 'kv', 'persistence', 'essential'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-memory"]}',
        true,
        980,
        4.7,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
        '0.3.0'
    ),
    (
        'brave-search',
        'Brave Search',
        'Web search capabilities powered by Brave Search API. Enables AI agents to search the web and retrieve current information.',
        NULL,
        '@modelcontextprotocol/server-brave-search',
        'search',
        ARRAY['search', 'web', 'api'],
        'stdio',
        ARRAY['tools'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-brave-search"], "env": {"BRAVE_API_KEY": "your-api-key"}}',
        true,
        850,
        4.6,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
        '0.3.0'
    ),
    (
        'fetch',
        'Fetch',
        'Fetch and process web content from URLs. Useful for retrieving and analyzing web pages, APIs, and online resources.',
        NULL,
        '@modelcontextprotocol/server-fetch',
        'search',
        ARRAY['web', 'http', 'fetch', 'essential'],
        'stdio',
        ARRAY['tools'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-fetch"]}',
        true,
        920,
        4.5,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
        '0.3.0'
    ),
    (
        'postgres',
        'PostgreSQL',
        'PostgreSQL database connectivity and query execution. Connect AI agents to PostgreSQL databases for data analysis and manipulation.',
        NULL,
        '@modelcontextprotocol/server-postgres',
        'database',
        ARRAY['database', 'sql', 'postgres'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-postgres"], "env": {"POSTGRES_URL": "postgresql://user:pass@host:5432/db"}}',
        true,
        780,
        4.7,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
        '0.3.0'
    ),
    (
        'github',
        'GitHub',
        'GitHub repository management and operations. Enables AI agents to interact with GitHub repositories, issues, and pull requests.',
        NULL,
        '@modelcontextprotocol/server-github',
        'development',
        ARRAY['git', 'github', 'vcs'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-github"], "env": {"GITHUB_TOKEN": "your-token"}}',
        true,
        690,
        4.6,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/github',
        '0.4.0'
    ),
    (
        'slack',
        'Slack',
        'Slack workspace integration and messaging. Connect AI agents to Slack for team communication and automation.',
        NULL,
        '@modelcontextprotocol/server-slack',
        'communication',
        ARRAY['chat', 'messaging', 'team'],
        'stdio',
        ARRAY['tools'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-slack"], "env": {"SLACK_BOT_TOKEN": "your-token"}}',
        false,
        450,
        4.4,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
        '0.2.0'
    ),
    (
        'puppeteer',
        'Puppeteer',
        'Browser automation and web scraping. Allows AI agents to control browsers, take screenshots, and extract data from websites.',
        NULL,
        '@modelcontextprotocol/server-puppeteer',
        'development',
        ARRAY['browser', 'automation', 'scraping'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-puppeteer"]}',
        false,
        520,
        4.5,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
        '0.3.0'
    ),
    (
        'google-drive',
        'Google Drive',
        'Google Drive file management and operations. Enables AI agents to access, search, and manipulate files in Google Drive.',
        NULL,
        '@modelcontextprotocol/server-gdrive',
        'storage',
        ARRAY['cloud', 'storage', 'files'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-gdrive"], "env": {"GOOGLE_CLIENT_ID": "your-id", "GOOGLE_CLIENT_SECRET": "your-secret"}}',
        false,
        380,
        4.3,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive',
        '0.2.0'
    ),
    (
        'sqlite',
        'SQLite',
        'SQLite database operations and queries. Lightweight database access for AI agents to work with local SQLite databases.',
        NULL,
        '@modelcontextprotocol/server-sqlite',
        'database',
        ARRAY['database', 'sql', 'sqlite', 'local'],
        'stdio',
        ARRAY['tools', 'resources'],
        '{"protocol": "stdio", "command": "npx", "args": ["-y", "@modelcontextprotocol/server-sqlite", "/path/to/database.db"]}',
        false,
        640,
        4.4,
        'Anthropic',
        'https://github.com/modelcontextprotocol/servers',
        'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
        '0.3.0'
    )
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    docker_image = EXCLUDED.docker_image,
    npm_package = EXCLUDED.npm_package,
    category = EXCLUDED.category,
    tags = EXCLUDED.tags,
    protocol = EXCLUDED.protocol,
    capabilities = EXCLUDED.capabilities,
    config_template = EXCLUDED.config_template,
    featured = EXCLUDED.featured,
    rating = EXCLUDED.rating,
    author = EXCLUDED.author,
    repository_url = EXCLUDED.repository_url,
    documentation_url = EXCLUDED.documentation_url,
    version = EXCLUDED.version;
