import { WorkflowTemplate } from './types';

export const mockTemplates: WorkflowTemplate[] = [
  {
    id: 'template-1',
    name: 'GitHub Issue Tracker',
    description: 'Automatically track GitHub issues and sync with your database. Creates notifications for new issues and updates.',
    category: 'Data Engineering',
    author: 'MCP Team',
    downloads: 1250,
    rating: 4.8,
    tags: ['github', 'database', 'automation'],
    version: '1.2.0',
    requiredServers: ['mcp-server-github', 'mcp-server-postgres'],
    workflow: {},
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-10-01T14:30:00Z',
  },
  {
    id: 'template-2',
    name: 'Slack Alert System',
    description: 'Monitor server health and send alerts to Slack channels when issues are detected. Includes escalation policies.',
    category: 'Monitoring & Alerts',
    author: 'DevOps Pro',
    downloads: 890,
    rating: 4.6,
    tags: ['slack', 'monitoring', 'alerts'],
    version: '2.0.1',
    requiredServers: ['mcp-server-slack', 'mcp-server-prometheus'],
    workflow: {},
    createdAt: '2025-08-20T08:15:00Z',
    updatedAt: '2025-09-28T16:45:00Z',
  },
  {
    id: 'template-3',
    name: 'AI Content Generator',
    description: 'Generate blog posts, social media content, and marketing copy using AI. Supports multiple formats and tone customization.',
    category: 'Content Generation',
    author: 'Content AI Labs',
    downloads: 2340,
    rating: 4.9,
    tags: ['ai', 'content', 'marketing', 'openai'],
    version: '1.5.0',
    requiredServers: ['mcp-server-openai', 'mcp-server-filesystem'],
    workflow: {},
    createdAt: '2025-07-10T12:00:00Z',
    updatedAt: '2025-10-05T09:20:00Z',
  },
  {
    id: 'template-4',
    name: 'Customer Support Automation',
    description: 'Automate customer support ticket routing and responses. Integrates with Zendesk, email, and knowledge base.',
    category: 'Customer Support',
    author: 'Support Team',
    downloads: 675,
    rating: 4.5,
    tags: ['support', 'automation', 'zendesk'],
    version: '1.1.0',
    requiredServers: ['mcp-server-zendesk', 'mcp-server-email'],
    workflow: {},
    createdAt: '2025-09-01T11:30:00Z',
    updatedAt: '2025-09-25T13:15:00Z',
  },
  {
    id: 'template-5',
    name: 'Email Campaign Manager',
    description: 'Schedule and send email campaigns with personalization. Track opens, clicks, and conversions automatically.',
    category: 'Marketing Automation',
    author: 'Marketing Genius',
    downloads: 1560,
    rating: 4.7,
    tags: ['email', 'marketing', 'campaigns'],
    version: '2.1.0',
    requiredServers: ['mcp-server-sendgrid', 'mcp-server-analytics'],
    workflow: {},
    createdAt: '2025-06-15T09:00:00Z',
    updatedAt: '2025-10-02T10:30:00Z',
  },
  {
    id: 'template-6',
    name: 'CI/CD Pipeline Monitor',
    description: 'Monitor CI/CD pipelines across multiple platforms. Get notified of build failures and deployment issues.',
    category: 'DevOps',
    author: 'DevOps Ninja',
    downloads: 980,
    rating: 4.8,
    tags: ['cicd', 'devops', 'monitoring'],
    version: '1.3.0',
    requiredServers: ['mcp-server-github', 'mcp-server-gitlab', 'mcp-server-slack'],
    workflow: {},
    createdAt: '2025-08-05T14:20:00Z',
    updatedAt: '2025-09-30T15:45:00Z',
  },
  {
    id: 'template-7',
    name: 'Data Backup & Sync',
    description: 'Automated data backup and synchronization across multiple storage providers. Includes encryption and versioning.',
    category: 'Data Engineering',
    author: 'Data Guardian',
    downloads: 1120,
    rating: 4.6,
    tags: ['backup', 'sync', 'storage'],
    version: '1.0.5',
    requiredServers: ['mcp-server-s3', 'mcp-server-filesystem'],
    workflow: {},
    createdAt: '2025-09-10T16:00:00Z',
    updatedAt: '2025-09-29T11:20:00Z',
  },
  {
    id: 'template-8',
    name: 'Social Media Scheduler',
    description: 'Schedule and publish content across multiple social media platforms. Includes analytics and engagement tracking.',
    category: 'Marketing Automation',
    author: 'Social Pro',
    downloads: 1890,
    rating: 4.9,
    tags: ['social-media', 'scheduling', 'marketing'],
    version: '2.2.0',
    requiredServers: ['mcp-server-twitter', 'mcp-server-facebook', 'mcp-server-instagram'],
    workflow: {},
    createdAt: '2025-07-20T10:30:00Z',
    updatedAt: '2025-10-04T14:00:00Z',
  },
  {
    id: 'template-9',
    name: 'Log Aggregation System',
    description: 'Collect, parse, and analyze logs from multiple sources. Create alerts based on log patterns and anomalies.',
    category: 'Monitoring & Alerts',
    author: 'LogMaster',
    downloads: 745,
    rating: 4.4,
    tags: ['logs', 'monitoring', 'analytics'],
    version: '1.4.0',
    requiredServers: ['mcp-server-elasticsearch', 'mcp-server-filesystem'],
    workflow: {},
    createdAt: '2025-08-12T13:45:00Z',
    updatedAt: '2025-09-27T09:15:00Z',
  },
  {
    id: 'template-10',
    name: 'Document Generator',
    description: 'Generate PDF documents, reports, and invoices from templates. Supports dynamic data and customizable layouts.',
    category: 'Content Generation',
    author: 'DocGen Inc',
    downloads: 1340,
    rating: 4.7,
    tags: ['pdf', 'documents', 'reports'],
    version: '1.6.0',
    requiredServers: ['mcp-server-pdf', 'mcp-server-filesystem'],
    workflow: {},
    createdAt: '2025-07-05T15:20:00Z',
    updatedAt: '2025-10-03T12:40:00Z',
  },
  {
    id: 'template-11',
    name: 'Database ETL Pipeline',
    description: 'Extract, transform, and load data between different databases. Supports scheduling and incremental updates.',
    category: 'Data Engineering',
    author: 'ETL Expert',
    downloads: 890,
    rating: 4.5,
    tags: ['etl', 'database', 'migration'],
    version: '1.1.0',
    requiredServers: ['mcp-server-postgres', 'mcp-server-mysql'],
    workflow: {},
    createdAt: '2025-08-25T11:00:00Z',
    updatedAt: '2025-09-26T14:30:00Z',
  },
  {
    id: 'template-12',
    name: 'Infrastructure Cost Monitor',
    description: 'Track cloud infrastructure costs and send budget alerts. Provides detailed cost breakdowns and recommendations.',
    category: 'DevOps',
    author: 'CloudSaver',
    downloads: 1450,
    rating: 4.8,
    tags: ['aws', 'cost', 'monitoring'],
    version: '2.0.0',
    requiredServers: ['mcp-server-aws', 'mcp-server-slack'],
    workflow: {},
    createdAt: '2025-06-30T09:30:00Z',
    updatedAt: '2025-10-01T16:20:00Z',
  },
  {
    id: 'template-13',
    name: 'Customer Feedback Analyzer',
    description: 'Collect and analyze customer feedback using AI. Generates sentiment analysis and actionable insights.',
    category: 'Customer Support',
    author: 'Feedback AI',
    downloads: 620,
    rating: 4.6,
    tags: ['feedback', 'ai', 'sentiment'],
    version: '1.2.0',
    requiredServers: ['mcp-server-openai', 'mcp-server-postgres'],
    workflow: {},
    createdAt: '2025-09-05T12:15:00Z',
    updatedAt: '2025-09-28T10:45:00Z',
  },
  {
    id: 'template-14',
    name: 'Security Vulnerability Scanner',
    description: 'Scan code repositories for security vulnerabilities. Integrates with security databases and creates tickets.',
    category: 'DevOps',
    author: 'SecOps Team',
    downloads: 1150,
    rating: 4.9,
    tags: ['security', 'scanning', 'vulnerabilities'],
    version: '1.7.0',
    requiredServers: ['mcp-server-github', 'mcp-server-snyk'],
    workflow: {},
    createdAt: '2025-07-15T14:00:00Z',
    updatedAt: '2025-10-06T11:30:00Z',
  },
  {
    id: 'template-15',
    name: 'Inventory Management System',
    description: 'Track inventory levels and automate reordering. Sends alerts for low stock and generates purchase orders.',
    category: 'Data Engineering',
    author: 'Inventory Pro',
    downloads: 530,
    rating: 4.4,
    tags: ['inventory', 'automation', 'erp'],
    version: '1.0.0',
    requiredServers: ['mcp-server-postgres', 'mcp-server-email'],
    workflow: {},
    createdAt: '2025-09-12T10:00:00Z',
    updatedAt: '2025-09-24T15:00:00Z',
  },
];

export const templateCategories = [
  {
    id: 'all',
    name: 'All Templates',
    icon: 'Squares2X2Icon',
    count: mockTemplates.length,
  },
  {
    id: 'data-engineering',
    name: 'Data Engineering',
    icon: 'CircleStackIcon',
    count: mockTemplates.filter(t => t.category === 'Data Engineering').length,
  },
  {
    id: 'monitoring-alerts',
    name: 'Monitoring & Alerts',
    icon: 'BellAlertIcon',
    count: mockTemplates.filter(t => t.category === 'Monitoring & Alerts').length,
  },
  {
    id: 'content-generation',
    name: 'Content Generation',
    icon: 'DocumentTextIcon',
    count: mockTemplates.filter(t => t.category === 'Content Generation').length,
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    icon: 'ChatBubbleLeftRightIcon',
    count: mockTemplates.filter(t => t.category === 'Customer Support').length,
  },
  {
    id: 'marketing-automation',
    name: 'Marketing Automation',
    icon: 'MegaphoneIcon',
    count: mockTemplates.filter(t => t.category === 'Marketing Automation').length,
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: 'CodeBracketIcon',
    count: mockTemplates.filter(t => t.category === 'DevOps').length,
  },
];
